config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :motos do
    resources :bookings, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [ :show, :edit, :update, :destroy ]
  patch 'booking/:id/accept', to: 'bookings#accept', as: 'accept'
  patch 'booking/:id/decline', to: 'bookings#decline', as: 'decline'
  get "profile", to: 'dashboards#profile'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :moto

  validates :moto, presence: true
  validates :user, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @moto = Moto.find(params[:moto_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @moto = Moto.find(params[:moto_id])
    @booking.moto = @moto
    @booking.user_id = current_user.id
    @booking.status = "Pending"
    if @booking.save!
      redirect_to profile_path
    else
      render :new
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "Accepted"
    @booking.save!
    redirect_to profile_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save!
    redirect_to profile_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to profile_path
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :moto_id)
  end
end

app/views/bookings/edit.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.yamaha-motor.eu/content/dam/fr-assets/t%C3%A9n%C3%A9r%C3%A9-700-center/trail-rando/2019_Trail_Rando_Diagonale_Tenere_700_245.jpg/_jcr_content/renditions/cq5dam.web.2000.2000.jpeg);">
  <div class="container">
    <h1><%= @booking.moto.brand %> <strong><%= @booking.moto.power %> Chevaux</strong> !</h1>
  </div>
</div>

<div class="container">
 <div class="form-wrapper" style="width: 600px; margin: 0 auto;">
    <h2>Edit Your Booking</h2>

    <%= simple_form_for(@booking) do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Make a Booking", class: "new-moto mb-3" %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.yamaha-motor.eu/content/dam/fr-assets/t%C3%A9n%C3%A9r%C3%A9-700-center/trail-rando/2019_Trail_Rando_Diagonale_Tenere_700_245.jpg/_jcr_content/renditions/cq5dam.web.2000.2000.jpeg);">
  <div class="container">
    <h1><%= @moto.brand %> <strong><%= @moto.power %> Chevaux</strong> !</h1>
  </div>
</div>

<div class="container">
  <div class="form-wrapper" style="width: 600px; margin: 0 auto;">
    <h2>Book a Moto</h2>
    <div data-controller="flatpicker">
      <%= simple_form_for([@moto, @booking]) do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, "Make a Booking", class: "new-moto mb-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Show booking</h1>

<div class="container"></div>

<p> <%= link_to 'New booking' , new_user_booking_path(@user), :class => "btn btn-primary" %> </p>

<div class="container">
  <div class="row mt-4">
    <% @list.bookings.each do |booking| %>
      <div class="col-4">
        <div class="card-category">
          <div class="card-product-img">
          </div>
          <div class="card-product-info">
            <p> <%= booking.start_date %> </p>
            <p> <%= booking.end_date %> </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>