config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :motos do
    resources :bookings, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [ :show, :edit, :update, :destroy ]
  patch 'booking/:id/accept', to: 'bookings#accept', as: 'accept'
  patch 'booking/:id/decline', to: 'bookings#decline', as: 'decline'
  get "profile", to: 'dashboards#profile'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def profile
    @my_bookings = Booking.where(user_id: current_user)
    @their_bookings = Booking.where(moto: current_user.motos)
    @user = current_user
    @motos = Moto.where(user_id: current_user)
  end
end

app/views/dashboards/profile.html.erb
<div class="Container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.midilibre.fr/api/v1/images/view/61def9638fe56f5eb81849b6/large/image.jpg?v=1)">
    <div class="container">
     <h1>Hey <%= current_user.first_name %>!</h1>
     <h2>Welcome to your Workshop!</h2>
    </div>
  </div>
</div>

<div class="container mt-4">
  <h2>Reservation on your Moto</h2>
  <% if @their_bookings.present? %>
    <div class="row">
      <% @their_bookings.each do |booking| %>
        <div class="col-4 mt-4">
          <div class="card-moto">
            <div class="card-moto-img-booking">
              <%= cl_image_tag booking.moto.photo.key, height: 300, width: 400, crop: :fill%>
              <% if booking.status == "Pending" %>
                <p id="status"> <%= booking.status %> </p>
                <%= link_to accept_path(booking), method: :patch, data: {confirm: "Certain d accepter?"} do %>
                  <i class="fas fa-check"></i>
                <% end %>
                <%= link_to decline_path(booking), method: :patch, data: {confirm: "Certain de refuser??"} do %>
                <i class="fas fa-times"></i>
                <% end %>
              <% elsif booking.status == "Accepted" %>
                <p id="status"> You <%= booking.status %> </p>
              <% elsif booking.status == "Declined" %>
                <p id="status"> You <%= booking.status %> </p>
              <% end %>

            </div>
            <div class="card-moto-info-booking">
              <p id="start-date">From: <strong> <%= booking.start_date %> </strong> </p>
              <p id="end-date">To: <strong> <%= booking.end_date %> </strong>  </p>
              <p id="revenue">Revenue: <strong> <%= (booking.end_date - booking.start_date).to_i * booking.moto.price %> € </strong> </p>
              <p id="day">For: <strong> <%= (booking.end_date - booking.start_date).to_i %> days </strong> </p>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="row">
      <div class="col-12 mt-4">
        <div class="nothing-info">
          <p>You don't have a reservation request yet</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container mt-4">
  <h2>Your Own Trips </h2>
  <% if @my_bookings.present? %>
    <div class="row">
      <% @my_bookings.each do |booking| %>
        <div class="col-4 mt-4">
          <div class="card-moto mt-2">
            <div class="card-moto-img-trip">
              <%= cl_image_tag booking.moto.photo.key, height: 300, width: 400, crop: :fill%>
              <%=  link_to booking_path(booking), method: :delete, data: {confirm: "Are you sure ?"} do %>
                <i class="fas fa-trash"></i>
              <% end %>
              <%= link_to edit_booking_path(booking) do %>
                <i class="fas fa-pen"></i>
              <% end %>

              <% if booking.status == "Accepted" %>
                <div class="loop validate"></div>
              <% elsif booking.status == "Declined" %>
                <div class="loop decline"></div>
              <% elsif booking.status == "Pending" %>
                <div class="loop"></div>
              <% end %>


            </div>
            <div class="card-moto-info-booking">
              <p id="start-date">From: <strong> <%= booking.start_date %> </strong> </p>
              <p id="end-date">To: <strong> <%= booking.end_date %> </strong>  </p>
              <p id="revenue">Trip cost: <strong> <%= (booking.end_date - booking.start_date).to_i * booking.moto.price %> € </strong></p>
              <p id="day">For: <strong> <%= (booking.end_date - booking.start_date).to_i %> days </strong> </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="row">
      <div class="col-12 mt-4">
        <div class="nothing-info">
          <p>You don't have a booking yet</p>
            <%= link_to "Go to the Garage", motos_path, class: "new-moto mt-3"  %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container mt-4">
  <h2>My Motos</h2>
  <% if @motos.present? %>
    <div class="row mt-4">
      <% @motos.each do |moto| %>
        <div class="col-4 mt-4">
          <div class="card-moto">
            <div class="card-my-moto-img">
              <%= cl_image_tag moto.photo.key, height: 300, width: 400, crop: :fill %>
              <%=  link_to moto_path(moto), method: :delete, data: {confirm: "Are you sure ?"} do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
            <div class="card-moto-info">
              <p> <%= link_to moto.name, moto_path(moto), :class => "name" %> </p>
              <p id="brand"> <%= moto.brand %> </p>
              <p id="power"> <%= moto.power %> Horsepower</p>
              <p id="kilometer"> <%= moto.kilometers %> Km</p>
              <p id="address"> <strong> <%= moto.address%> </strong> </p>
              <p id="username"> <%= moto.user.first_name %> <%= moto.user.last_name %> </p>
              <p id="price"> <strong> <%= moto.price%> € </strong> </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="row mt-4">
      <div class="col-12">
        <div class="nothing-info">
          <p>You haven't added your Moto</p>
            <%= link_to "Create a Moto", new_moto_path, class: "new-moto mt-3"  %>
        </div>
      </div>

    </div>
  <% end %>
</div>

<div class="container mt-4">
  <h2>My profile</h2>
  <%= simple_form_for(@user, url: user_registration_path	) do |f| %>
  <div class="row">
    <div class="col-6">
      <%= f.input :first_name %>
    </div>
    <div class="col-6">
      <%= f.input :last_name %>
    </div>
  </div>
    <%= f.input :email %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Update my profile", class: "new-moto mb-3" %>
  <% end %>

</div>