config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :motos do
    resources :bookings, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [ :show, :edit, :update, :destroy ]
  patch 'booking/:id/accept', to: 'bookings#accept', as: 'accept'
  patch 'booking/:id/decline', to: 'bookings#decline', as: 'decline'
  get "profile", to: 'dashboards#profile'
end

app/models/moto.rb
class Moto < ApplicationRecord
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings

  validates :name, presence: true
  validates :brand, presence: true
  validates :address, presence: true
  validates :power, presence: true
  validates :kilometers, presence: true
  validates :price, presence: true
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_brand_and_address,
    against: [ :brand, :address ],
    using: {
      tsearch: { prefix: true }
    }
  def average
    ratings = self.reviews.map do |review|
      review.rating.to_f
    end
    ratings.sum/ratings.length
  end
end

app/controllers/motos_controller.rb
class MotosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def new
    @moto = Moto.new
  end

  def index
    if params[:query].present?
      @motos = Moto.search_by_brand_and_address(params[:query])
    else
      @motos = Moto.all
    end

    @markers = @motos.geocoded.map do |moto|
      {
        lat: moto.latitude,
        lng: moto.longitude,
        infos_window: render_to_string(partial: "infos_window", locals: { moto: moto }),
        image_url: helpers.asset_url("icone_moto.png")
      }
    end
  end

  def show
    @moto = Moto.find(params[:id])
    @average_rating = @moto.reviews.average(:rating)
  end

  def create
    @moto = Moto.new(moto_params)
    @moto.user_id = current_user.id
    if @moto.save!
      redirect_to motos_path
    else
      render :new
    end
  end

  def edit
    @moto = Moto.find(params[:id])
  end

  def update
    @moto = Moto.find(params[:id])
    @moto.update(moto_params)
    redirect_to moto_path(@moto)
  end

  def destroy
    @moto = Moto.find(params[:id])
    @moto.destroy
    redirect_to profile_path
  end

  private

  def moto_params
    params.require(:moto).permit(:name, :brand, :address, :price, :available, :power, :kilometers, :user_id, :photo)
  end
end

app/views/motos/_infos_window.html.erb
<div class="container">
  <div class="notif">
    <%= link_to moto_path(moto), class: "deco-notif" do %>
      <h2><%= moto.brand %></h2>
    <%end%>
    <h6><%= moto.address.capitalize %></h6>
    <h6>Price: <%= moto.price %> € / day</h6>
  </div>
</div>

app/views/motos/edit.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.yamaha-motor.eu/content/dam/fr-assets/t%C3%A9n%C3%A9r%C3%A9-700-center/trail-rando/2019_Trail_Rando_Diagonale_Tenere_700_245.jpg/_jcr_content/renditions/cq5dam.web.2000.2000.jpeg);">
  <div class="container">
  </div>
</div>

<div class="container">
  <h1> Update your dear <%= @moto.brand%></h1>
  <%= simple_form_for(@moto) do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>
    <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: "d-none"  },
              wrapper_html: { data: { controller: "geocoder",
  geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.input :power %>
  <%= f.input :kilometers %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Update", class: "new-moto mt-3" %>
  <% end %>
</div>

app/views/motos/index.html.erb
<div class="banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.yamaha-motor.eu/content/dam/fr-assets/t%C3%A9n%C3%A9r%C3%A9-700-center/trail-rando/2019_Trail_Rando_Diagonale_Tenere_700_245.jpg/_jcr_content/renditions/cq5dam.web.2000.2000.jpeg);">
  <div class="container">

  </div>
</div>



  <div class="container mb-3">
    <div class="row">
      <h2> Available Motos</h2>
       <div class="col-12 col-lg-6">
        <div class="row align-search">
          <div class="col-12 col-lg-9">
            <%= form_tag motos_path, method: :get do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a moto"
            %>
          </div>
          <div class="col-12 col-lg-3">
            <%= submit_tag "Search", class: "new-moto my-3" %>
            <% end %>
          </div>
        </div>

        <% @motos.each do |moto| %>
          <div class="card-product mb-3">
            <%= cl_image_tag(moto.photo.key, height: 300, width: 400, crop: :fill)%>
            <div class="card-product-infos">
              <%= link_to moto_path(moto), class:"link-without-style" do %>
              <h2 id="brand"> <%= moto.brand %> </h2>
              <% end %>

              <p id="power">Power: <%= moto.power %>CC</p>
              <p id="kilometers">Kilometers: <%= moto.kilometers %> Kms</p>
              <p id="name"><strong><%= moto.name %></strong></p>
              <p id="card-price">For only <strong><%= moto.price %> €</strong></p>
              <p id="place"><strong><%= moto.address %></strong></p>
              <% if moto.reviews.count > 0 %>
                <% moto.average.truncate(1) %>
              <div class="reviews">
                <p id="reviews">
                  <% Review::AUTHORIZED_RATINGS.each do |number| %>
                  <% count = 0 %>
                  <% break if count > 1 %>
                  <i class="fa<%= (number > moto.average.truncate(1)) ? 'r' : 's' %> fa-star"></i>
                  <% count += 1%>
                  <% end %>
                </p>
              </div>
              <% else %>
                <p id="reviews">No ratings yet</p>
              <% end %>
            </div>
          </div>

        <% end %>
      </div>

       <div id="map" class= "col-12 col-lg-6 mb-3" style= "height: 750px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
 </div>

app/views/motos/new.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.yamaha-motor.eu/content/dam/fr-assets/t%C3%A9n%C3%A9r%C3%A9-700-center/trail-rando/2019_Trail_Rando_Diagonale_Tenere_700_245.jpg/_jcr_content/renditions/cq5dam.web.2000.2000.jpeg);">
    <div class="container">
      <h2>Create your moto here and make money!</h2>
    </div>
</div>

<div class="container">
  <h1> Create your Moto</h1>
  <%= simple_form_for(@moto) do |f| %>
  <div class="row">
    <div class="col-6">
      <%= f.input :name %>
    </div>
    <div class="col-6">
      <%= f.input :brand %>
    </div>
  </div>
  <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: "d-none"  },
              wrapper_html: { data: { controller: "geocoder",
  geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.input :power %>
  <%= f.input :kilometers %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create your Moto", class: "new-moto mb-3" %>
  <% end %>
</div>

app/views/motos/show.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.yamaha-motor.eu/content/dam/fr-assets/t%C3%A9n%C3%A9r%C3%A9-700-center/trail-rando/2019_Trail_Rando_Diagonale_Tenere_700_245.jpg/_jcr_content/renditions/cq5dam.web.2000.2000.jpeg);">
  <div class="container">
    <h1>Hey <%= current_user.first_name %>!</h1>
    <h2><strong>Make a Reservation on This Bike</strong> !</h2>
  </div>
</div>


<div class="container">
  <div class="card-trip mb-3">
    <%= cl_image_tag @moto.photo.key, height: 800, width: 900, crop: :fill%>
    <div class="card-trip-infos mb-3">
      <div>
        <h2><%= @moto.brand %> </h2>
        <p><%= @moto.power %> Horsepower</p>
        <p><%= @moto.kilometers %> Km</p>

        <p>Location: <%= @moto.address %></p>
        <% if @moto.reviews.count > 0 %>
          <p>Rating: <%= @average_rating.truncate(1) %>/5 -- <%=@moto.reviews.count%> comments</p>
          <div class="reviews">
            <p>
              <% Review::AUTHORIZED_RATINGS.each do |number| %>
              <% count = 0 %>
              <% break if count > 1 %>
              <i class="fa<%= (number > @average_rating) ? 'r' : 's' %> fa-star"></i>
              <% count += 1%>
              <% end %>
            </p>
          </div>
          <% else %>
            <p>No ratings yet</p>
          <% end %>
      </div>
      <div>
        <%= link_to "Reserve bike now", new_moto_booking_path(@moto), class: "new-moto" %>
        <%= link_to "Leave a review", new_moto_review_path(@moto), class: "new-moto" %>
      </div>

      <% if @moto.user_id == current_user.id %>
        <div>
          <%= link_to "Delete this Bike", moto_path(@moto), method: :delete, class: "new-moto-show" %>
        </div>
        <div>
          <%= link_to "Update Bike", edit_moto_path(@moto), class: "new-moto-show" %>
        </div>
      <% end %>

      <h3 class="card-trip-pricing"><%= @moto.price %>€</h2>
    </div>
  </div>
</div>

  <div class="container mb-3">
     <%= link_to "Back to Motos", motos_path, class: "new-moto my-3"  %>
  </div>